# Typos configuration for clojure-skills project
# See: https://github.com/crate-ci/typos

[default.extend-words]
# EDN is a valid Clojure file format (Extensible Data Notation)
edn = "edn"

# "caf√©" in French when percent-encoded shows as "caf" in examples
caf = "caf"
Caf = "Caf"

# core.logic function names
matche = "matche"

# Clojure function names
juxt = "juxt"
uncomplete = "uncomplete"

[files]
# Respect gitignore by default
ignore-vcs = false

# Don't check generated or cache directories
extend-exclude = [
  "_build/",
  ".cpcache/",
  ".clj-kondo/.cache/",
  ".lsp/",
  "classes/",
]
